//! ModSecurity WAF Detection Provider

use crate::{DetectionContext, DetectionProvider, Evidence, MethodType, ProviderType};
use anyhow::Result;
use regex::Regex;
use std::sync::OnceLock;

/// ModSecurity detection provider
#[derive(Debug, Clone)]
pub struct ModSecurityProvider {
    name: String,
    version: String,
    description: String,
    enabled: bool,
}

impl ModSecurityProvider {
    pub fn new() -> Self {
        Self {
            name: "ModSecurity".to_string(),
            version: "1.0.0".to_string(),
            description: "ModSecurity open-source WAF detection provider".to_string(),
            enabled: true,
        }
    }

    // Pre-compiled regex patterns for performance
    fn mod_security_server_pattern() -> &'static Regex {
        static PATTERN: OnceLock<Regex> = OnceLock::new();
        PATTERN.get_or_init(|| Regex::new(r"(?i)mod_security").unwrap())
    }

    fn noyb_server_pattern() -> &'static Regex {
        static PATTERN: OnceLock<Regex> = OnceLock::new();
        PATTERN.get_or_init(|| Regex::new(r"(?i)NOYB").unwrap())
    }

    fn modsecurity_body_pattern() -> &'static Regex {
        static PATTERN: OnceLock<Regex> = OnceLock::new();
        PATTERN.get_or_init(|| Regex::new(r"(?i)(modsecurity|mod_security)").unwrap())
    }

    fn modsecurity_error_pattern() -> &'static Regex {
        static PATTERN: OnceLock<Regex> = OnceLock::new();
        PATTERN.get_or_init(|| Regex::new(r"(?i)this error was generated by mod_security").unwrap())
    }

    fn modsecurity_action_pattern() -> &'static Regex {
        static PATTERN: OnceLock<Regex> = OnceLock::new();
        PATTERN.get_or_init(|| Regex::new(r"(?i)modsecurity (action|rule)").unwrap())
    }

    fn not_acceptable_pattern() -> &'static Regex {
        static PATTERN: OnceLock<Regex> = OnceLock::new();
        PATTERN.get_or_init(|| Regex::new(r"(?i)not acceptable").unwrap())
    }

    async fn check_headers(&self, response: &crate::http::HttpResponse) -> Vec<Evidence> {
        let mut evidence = Vec::new();

        // Check Server header for mod_security or NOYB (common ServerTokens setting)
        if let Some(server) = response.headers.get("server") {
            if Self::mod_security_server_pattern().is_match(server) {
                evidence.push(Evidence {
                    method_type: MethodType::Header("server".to_string()),
                    confidence: 0.90,
                    description: "ModSecurity Server header detected".to_string(),
                    raw_data: server.clone(),
                    signature_matched: "modsecurity-server-header".to_string(),
                });
            } else if Self::noyb_server_pattern().is_match(server) {
                evidence.push(Evidence {
                    method_type: MethodType::Header("server".to_string()),
                    confidence: 0.90,
                    description:
                        "NOYB Server header detected (common ModSecurity ServerTokens setting)"
                            .to_string(),
                    raw_data: server.clone(),
                    signature_matched: "modsecurity-noyb-header".to_string(),
                });
            }
        }

        // Check X-Mod-Security header (extremely rare but definitive)
        if let Some(x_mod_security) = response.headers.get("x-mod-security") {
            evidence.push(Evidence {
                method_type: MethodType::Header("x-mod-security".to_string()),
                confidence: 0.98,
                description: "X-Mod-Security header detected".to_string(),
                raw_data: x_mod_security.clone(),
                signature_matched: "modsecurity-header".to_string(),
            });
        }

        // Check X-ModSecurity header variant
        if let Some(x_modsecurity) = response.headers.get("x-modsecurity") {
            evidence.push(Evidence {
                method_type: MethodType::Header("x-modsecurity".to_string()),
                confidence: 0.98,
                description: "X-ModSecurity header detected".to_string(),
                raw_data: x_modsecurity.clone(),
                signature_matched: "modsecurity-header".to_string(),
            });
        }

        evidence
    }

    async fn check_body_patterns(&self, response: &crate::http::HttpResponse) -> Vec<Evidence> {
        let mut evidence = Vec::new();

        // Check for ModSecurity error message
        if Self::modsecurity_error_pattern().is_match(&response.body) {
            evidence.push(Evidence {
                method_type: MethodType::Body("modsecurity-error-message".to_string()),
                confidence: 0.95,
                description: "ModSecurity error message detected".to_string(),
                raw_data: "modsecurity-error-detected".to_string(),
                signature_matched: "modsecurity-error-body".to_string(),
            });
        }

        // Check for ModSecurity Action or Rule references
        if Self::modsecurity_action_pattern().is_match(&response.body) {
            evidence.push(Evidence {
                method_type: MethodType::Body("modsecurity-action-reference".to_string()),
                confidence: 0.90,
                description: "ModSecurity Action/Rule reference found in response body".to_string(),
                raw_data: "modsecurity-action-detected".to_string(),
                signature_matched: "modsecurity-action-body".to_string(),
            });
        }

        // Check for generic ModSecurity references in body
        if Self::modsecurity_body_pattern().is_match(&response.body) {
            evidence.push(Evidence {
                method_type: MethodType::Body("modsecurity-reference".to_string()),
                confidence: 0.85,
                description: "ModSecurity reference found in response body".to_string(),
                raw_data: "modsecurity-reference-detected".to_string(),
                signature_matched: "modsecurity-body".to_string(),
            });
        }

        // Check for "Not Acceptable" with ModSecurity indicators
        if Self::not_acceptable_pattern().is_match(&response.body)
            && Self::modsecurity_body_pattern().is_match(&response.body)
        {
            evidence.push(Evidence {
                method_type: MethodType::Body("not-acceptable-modsecurity".to_string()),
                confidence: 0.80,
                description: "Not Acceptable message with ModSecurity indicators".to_string(),
                raw_data: "not-acceptable-modsecurity".to_string(),
                signature_matched: "modsecurity-not-acceptable-body".to_string(),
            });
        }

        evidence
    }

    async fn check_status_codes(&self, response: &crate::http::HttpResponse) -> Vec<Evidence> {
        let mut evidence = Vec::new();

        // Check for 406 Not Acceptable with ModSecurity body indicators
        if response.status == 406 && Self::modsecurity_body_pattern().is_match(&response.body) {
            evidence.push(Evidence {
                method_type: MethodType::StatusCode(406),
                confidence: 0.80,
                description: "ModSecurity 406 Not Acceptable response".to_string(),
                raw_data: "406".to_string(),
                signature_matched: "modsecurity-406-status".to_string(),
            });
        }

        // Check for 403 Forbidden with ModSecurity body indicators
        if response.status == 403 && Self::modsecurity_body_pattern().is_match(&response.body) {
            evidence.push(Evidence {
                method_type: MethodType::StatusCode(403),
                confidence: 0.75,
                description: "ModSecurity 403 Forbidden response".to_string(),
                raw_data: "403".to_string(),
                signature_matched: "modsecurity-403-status".to_string(),
            });
        }

        evidence
    }
}

#[async_trait::async_trait]
impl DetectionProvider for ModSecurityProvider {
    fn name(&self) -> &str {
        &self.name
    }

    fn version(&self) -> &str {
        &self.version
    }

    fn description(&self) -> Option<String> {
        Some(self.description.clone())
    }

    fn provider_type(&self) -> ProviderType {
        ProviderType::WAF
    }

    fn confidence_base(&self) -> f64 {
        0.90
    }

    fn priority(&self) -> u32 {
        85
    }

    fn enabled(&self) -> bool {
        self.enabled
    }

    async fn detect(&self, context: &DetectionContext) -> Result<Vec<Evidence>> {
        let mut all_evidence = Vec::new();

        if let Some(response) = &context.response {
            // Check headers
            let header_evidence = self.check_headers(response).await;
            all_evidence.extend(header_evidence);

            // Check body patterns
            let body_evidence = self.check_body_patterns(response).await;
            all_evidence.extend(body_evidence);

            // Check status codes
            let status_evidence = self.check_status_codes(response).await;
            all_evidence.extend(status_evidence);
        }

        Ok(all_evidence)
    }

    async fn passive_detect(&self, response: &crate::http::HttpResponse) -> Result<Vec<Evidence>> {
        let mut all_evidence = Vec::new();

        all_evidence.extend(self.check_headers(response).await);
        all_evidence.extend(self.check_body_patterns(response).await);
        all_evidence.extend(self.check_status_codes(response).await);

        Ok(all_evidence)
    }
}

impl Default for ModSecurityProvider {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::providers::test_utils::mock_response;

    #[tokio::test]
    async fn detects_modsecurity_x_mod_security_header() {
        let provider = ModSecurityProvider::new();
        let response = mock_response(200, [("x-mod-security", "1")], "");
        let evidence = provider.passive_detect(&response).await.unwrap();
        assert!(!evidence.is_empty());
        assert!(evidence
            .iter()
            .any(|e| e.signature_matched == "modsecurity-header"));
    }

    #[tokio::test]
    async fn detects_modsecurity_server_header() {
        let provider = ModSecurityProvider::new();
        let response = mock_response(200, [("server", "nginx/1.0 mod_security")], "");
        let evidence = provider.passive_detect(&response).await.unwrap();
        assert!(evidence
            .iter()
            .any(|e| e.signature_matched == "modsecurity-server-header"));
    }

    #[tokio::test]
    async fn detects_modsecurity_error_body() {
        let provider = ModSecurityProvider::new();
        let response = mock_response(
            403,
            vec![("content-type", "text/html")],
            "This error was generated by Mod_Security.",
        );
        let evidence = provider.passive_detect(&response).await.unwrap();
        assert!(evidence
            .iter()
            .any(|e| e.signature_matched == "modsecurity-error-body"));
    }

    #[tokio::test]
    async fn no_evidence_without_modsecurity_indicators() {
        let provider = ModSecurityProvider::new();
        let response = mock_response(200, [("server", "nginx")], "");
        let evidence = provider.passive_detect(&response).await.unwrap();
        assert!(evidence.is_empty());
    }
}
